spring:
  application:
    name: ag-gate
zuul:
  prefix: /api  #拦截所有以api大头的请求都经过zuul路由
  routes: # todo 路由表定义
    user-center:
      path: /uc/**
      serviceId: user-center
    auth-center:
      path: /auth/**
      serviceId: ag-auth
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8765


jwt:
  expire: 3600
  pri-key:
    path: D:\workspaces\IntelliJIDEA\ag-parent\ag-auth\src\main\resources\pri.key
  pub-key:
    path: D:\workspaces\IntelliJIDEA\ag-parent\ag-auth\src\main\resources\pub.key