spring:
  application:
    name: user-center

  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/ace?useUnicode=true&amp;characterEncoding=UTF-8&amp;autoReconnect=true&amp;failOverReadOnly=false
    username: root
    password: 123qwe
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
    basepackage: com.github.learning.uc.mapper
    xmlLocation: classpath:mapper/**/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 7771
info:
  appName: user-center

# sql语句
logging:
  level:
    com.github.learning.uc.mapper: debug
jwt:
  expire: 3600
  pub-key:
    path: D:\workspaces\IntelliJIDEA\ag-parent\ag-uc\src\main\resources\pub.key
  token-header: access-token
